name: CI-DevOpsBasico

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        
        - name: Setup do node.js
          uses: actions/setup-node@3.0.0
          with:
            node-version: 16.13.2
              
